// This file was auto generated for module System.Power
// This module was generated partially, because it is a dependency of another module

#module_parameters (UNICODE := true);


// Constants


// Types

POWER_SETTING_REGISTER_NOTIFICATION_FLAGS :: enum u32
{
    DEVICE_NOTIFY_SERVICE_HANDLE :: 1;
    DEVICE_NOTIFY_CALLBACK :: 2;
    DEVICE_NOTIFY_WINDOW_HANDLE :: 0;
}

// Functions


// Unicode aliases


// System libraries

#scope_file

