// This file was auto generated for module UI.Shell
// This module was generated partially, because it is a dependency of another module

#module_parameters (UNICODE := true);

#import "Win32/Foundation" (UNICODE);

// Constants


// Types

HELPINFO :: struct
{
    cbSize : u32;
    iContextType : s32;
    iCtrlId : s32;
    hItemHandle : HANDLE;
    dwContextId : u64;
    MousePos : POINT;
}

// Functions


// Unicode aliases


// System libraries

#scope_file

